version: "3"
services:
  tax_calculator:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: tax-calculator
    volumes:
      - .:/calculator
    restart: on-failure
    stdin_open: true
    tty: true
